version: '3.8'
 
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: rental
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"